function generateMarkdown(data) {
  return `# ${data.projectTitle}

  ![badge](https://img.shields.io/badge/license-${data.license}-brightgreen) </br>

  ## Table of Contents 

  - [Description](#description)
  - [Installation](#installation)
  - [Usage](#usage)
  - [License](#license)
  - [Contributing](#contributing)
  - [Tests](#tests)
  - [Future](#future)
  - [Questions](#questions)
  - [Contact](#contact)

  ## Description   
  📝
  
  ${data.description}

  ## Installation 
  🔽
  
  ${data.installation}

  ## Usage 
  💻
  
  ${data.usage}

  ##  License 
  ![badge](https://img.shields.io/badge/license-${data.license}-brightgreen) </br>
  📎
  
  ${data.projectTitle} is covered by the ${data.license} license.
  
  ## Contributing 
  👪
  
  ${data.contributors}

  ## Tests  
  📝
  
  ${data.test}
  
  ## Future  
  ⏩
  
  ${data.future}

  ## Questions  
  ❔
  
  ${data.questions}
  
  ## Contact
  Github: http://github.com/${data.username} </br>
  Email: ${data.email}


  ### This md file was generated by using the Do-Node-Readme application
`;
}

module.exports = generateMarkdown;
